import sys
import os
import json
import pandas as pd
from typing import List, Optional
from peptide_pipeline.dataloader.base import BaseDataLoader

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, PROJECT_ROOT)

AMINO_ACIDS = "ACDEFGHIKLMNPQRSTVWY"


class DataLoader(BaseDataLoader):
    """
    Data Loader Agent for peptide JSON data.
    Responsible for loading and preprocessing peptide data for training or evaluation.
    """

    def __init__(self):
        super().__init__()
        self.data = None
        self.logger.info("DataLoader initialized.")

    def load_data(
        self,
        source: str = "ai_training_peptides.json",
        columns: Optional[List[str]] = None,
        **kwargs
    ) -> None:
        """
        Loads data from a JSON file.

        Expected record fields:
        - SEQUENCE (required)
        - NAME (optional; autogenerated if missing)

        Supports:
        - JSON array of objects
        - JSONL (one JSON object per line)
        """
        try:
            if not os.path.isabs(source):
                source = os.path.join(PROJECT_ROOT, source)

            if not os.path.exists(source):
                raise FileNotFoundError(f"File not found: {source}")

            # Try standard JSON first
            try:
                self.data = pd.read_json(source)
            except ValueError:
                # Fallback to JSONL
                try:
                    self.data = pd.read_json(source, lines=True)
                except ValueError:
                    # Final fallback: manual JSON load
                    with open(source, "r", encoding="utf-8") as f:
                        raw = json.load(f)
                    self.data = pd.DataFrame(raw)

            # Normalize column names (case-insensitive)
            colmap = {c.lower(): c for c in self.data.columns}
            if "sequence" in colmap and "SEQUENCE" not in self.data.columns:
                self.data.rename(columns={colmap["sequence"]: "SEQUENCE"}, inplace=True)
            if "name" in colmap and "NAME" not in self.data.columns:
                self.data.rename(columns={colmap["name"]: "NAME"}, inplace=True)

            # Validate required fields
            if "SEQUENCE" not in self.data.columns:
                self.logger.error("JSON must contain a 'SEQUENCE' field.")
                raise ValueError("JSON must contain a 'SEQUENCE' field.")

            # Create NAME if missing
            if "NAME" not in self.data.columns:
                self.data["NAME"] = [f"peptide_{i}" for i in range(len(self.data))]

            self.logger.info(f"Data loaded successfully from {source}. Total records: {len(self.data)}")

            if columns is None:
                self.logger.info("No columns specified, defaulting to ['NAME', 'SEQUENCE']")
                columns = ["NAME", "SEQUENCE"]

            missing = [col for col in columns if col not in self.data.columns]
            if missing:
                self.logger.error(f"Requested columns not found in JSON: {missing}")
                raise ValueError(f"Requested columns not found in JSON: {missing}")

            self.data = self.data[columns]

        except Exception as e:
            self.logger.error(f"Error loading data: {e}")
            sys.exit(1)

    def get_data(self) -> pd.DataFrame:
        """
        Returns the loaded and processed data as a pandas DataFrame.
        """
        if self.data is None:
            self.logger.error("Data not loaded. Call load_data() first.")
            sys.exit(1)
        self.logger.info("Data retrieval successful.")
        return self.data